# Generated by Django 5.1.7 on 2025-03-28 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='peliculas/')),
                ('sinopsis', models.TextField(default='Sinopsis no disponible.')),
                ('genero', models.CharField(max_length=100)),
                ('formato', models.CharField(max_length=50)),
                ('estreno', models.BooleanField(default=False)),
                ('preventa', models.BooleanField(default=False)),
                ('trailer_url', models.URLField()),
                ('calificacion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo_sala', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('VIP', 'VIP')], default='2D', max_length=10)),
                ('capacidad', models.PositiveIntegerField(default=100)),
                ('filas', models.PositiveIntegerField(default=10)),
                ('columnas', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('tipo_documento', models.CharField(blank=True, max_length=50)),
                ('genero', models.CharField(blank=True, max_length=50)),
                ('documento', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='usuarios.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='usuarios.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('id_silla', models.AutoField(primary_key=True, serialize=False)),
                ('numero_silla', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible'), ('ocupada', 'Ocupada'), ('escogida', 'Escogida')], default='disponible', max_length=20)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sillas', to='usuarios.horario')),
                ('sala', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sillas', to='usuarios.sala')),
            ],
        ),
    ]
