# Generated by Django 5.1.7 on 2025-03-28 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silla',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='silla',
            name='numero_silla',
        ),
        migrations.AddField(
            model_name='silla',
            name='columna',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='silla',
            name='fila',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='silla',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no-disponible', 'No disponible'), ('ocupada', 'Ocupada')], default='disponible', max_length=15),
        ),
        migrations.AlterField(
            model_name='silla',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sillas', to='usuarios.sala'),
        ),
    ]
