# Generated by Django 5.1.7 on 2025-03-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía')], max_length=50),
        ),
    ]
