# Generated by Django 5.1.7 on 2025-04-03 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_pelicula_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='silla',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.horario'),
        ),
    ]
